#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys

class TinkerTemp(object):
    HOST = "localhost"
    PORT = 4223
    UID = "dJj" # Change to your UID

    def __init__(self,):
        from tinkerforge.bricklet_temperature import Temperature
        from tinkerforge.ip_connection        import IPConnection

        self._ipcon         = IPConnection() # Create IP connection
        self._temp_bricklet = Temperature(TinkerTemp.UID, self._ipcon) # Create device object

        self._connect()

    def _connect(self,):
        self._ipcon.connect(TinkerTemp.HOST, TinkerTemp.PORT) # Connect to brickd

    def read_temperature(self,):
        return self._temp_bricklet.get_temperature()/100.0

    def disconnect(self,):
        self._ipcon.disconnect()

class MuninTinkerTemp(object):
    def __init__(self,):
        self._tt = TinkerTemp()

    def config(self,):
        print """graph_title Room Temperature
graph_args --lower-limit 0 --upper-limit 50
graph_vlabel C
graph_scale no
graph_info This graph shows the temperature for room D114
graph_category temperature
graph_period second
temp.label temp
temp.draw AREA
temp.min 0
temp.type GAUGE
temp.info Room Temperature D114"""

    def fetch(self,):
        print 'temp.value %s' % self._tt.read_temperature()

if __name__ == "__main__":
    mtt = MuninTinkerTemp()

    try:
        if sys.argv[1] == 'config':
            mtt.config()
    except IndexError, e:
        mtt.fetch()
